### ISSUE TITLE
Running MKS DLC32 V2.1 without touch screen

### ISSUE THREAD

**Issue by deltazerorsan** [Macrobase-tech/MKS-DLC32#1]
Hi there,

I'm configuring my new board MKS DLC32 V2.1 for use with a CNC machine.

I just load de CNC version of the firmware using MKSLaserTool; everything correct.

But then I realized that there is no WiFi menu in this version of MKSLaserTool. My intention is to use the board directly attached via USB to the workshop computer and supervise it via WiFi through a browser or via your mobile app, so no touchscreen at all.

1. How can I configure the WiFi from the UGS (universal gcode sender) console?
2. where can I find your mobile App?

Thanks in advance!

Rom

**Comment by Macrobase-tech** [comment]
Hello Rom,
The wifi function is available with MKS TS24/TS35 display.
If without display,just DLC32,not work so far.
1.unable to enable by the UGS.
2.Please search MKSLASER on Google store,and download.











Best Regard!




&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Macrobase-tech/MKS-DLC32"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月5日(星期天) 凌晨3:10
***@***.***&gt;;
***@***.***&gt;;
主题:&nbsp;[Macrobase-tech/MKS-DLC32] Running MKS DLC32 V2.0 without touch screen (Issue #1)





 
Hi there,
 
I'm configuring my new board MKS DLC32 V2.0 for use with a CNC machine.
 
I just load de CNC version of the firmware using MKSLaserTool; everything correct.
 
But then I realized that there is no WiFi menu in this version of MKSLaserTool. My intention is to use the board directly attached via USB to the workshop computer and supervise it via WiFi through a browser or via your mobile app, so no touchscreen at all.
  
How can I configure the WiFi from the UGS (universal gcode sender) console?
 
where can I find your mobile App?
  
Thanks in advance!
 
Rom
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by deltazerorsan** [comment]
What a shame, the new board is really nice and, with the addition of the ESP32, very powerfull.

Why MKSLaserTool has not the WiFi menu? It is present in the documentation.

Is there the possibility to activate and configure WiFi via SD card?

Please let me know about any solution you can find.

Thanks!

Best regards,

Rom

**Comment by RandomHacks-Git** [comment]
Hi, check this https://github.com/makerbase-mks/MKS-DLC32/issues/12

**Comment by deltazerorsan** [comment]
> Hi, check this [makerbase-mks/MKS-DLC32#12](https://github.com/makerbase-mks/MKS-DLC32/issues/12)

Thanks a lot! The pointer is really valuable!

Rom

**Comment by Macrobase-tech** [comment]
Thank you for the Github link sharing,Makerbase is our supplier.
Activate and configure WiFi via SD card will be available in the feature.

&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "Macrobase-tech/MKS-DLC32"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年12月6日(星期一) 下午5:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [Macrobase-tech/MKS-DLC32] Running MKS DLC32 V2.1 without touch screen (Issue #1)





 
What a shame, the new board is really nice and, with the addition of the ESP32, very powerfull.
 
Why MKSLaserTool has not the WiFi menu? It is present in the documentation.
 
Is there the possibility to activate and configure WiFi via SD card?
 
Please let me know about any solution you can find.
 
Thanks!
 
Best regards,
 
Rom
 
—
You are receiving this because you commented.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.
